# Generated by Django 3.0 on 2019-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('apartment', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('phone', models.CharField(max_length=32)),
                ('food', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
