# Generated by Django 3.0 on 2020-05-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DishObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('availability', models.BooleanField()),
                ('cal', models.CharField(max_length=8)),
                ('fats', models.CharField(max_length=8)),
                ('carbo', models.CharField(max_length=8)),
                ('prot', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('img', models.ImageField(upload_to='')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories')),
            ],
        ),
    ]
